### ISSUE TITLE
Can you add to README what flight simulator is supported?

### ISSUE THREAD

**Issue by colourful-land** [nirenjan/x52pro-linux#15]
I don't know any other than X-plane 11 that runs in Linux, so maybe yours is tested against that. But it would be great to let users know up front what flight simulator are you testing against when you developed it.
 Thanks

**Comment by nirenjan** [comment]
I actually didn't test this against any flight simulator. The library is used by the front end CLI applications to control the LED and MFD.

That said, the joystick itself is quite usable by any flight simulator, since I don't do anything with the HID API.
