### ISSUE TITLE
Installation and config

### ISSUE THREAD

**Issue by mauricioduarte01** [nirenjan/x52pro-linux#16]
Hello.
First I would like to thank you for your effort programming this plugin. I would like to know if you can make a step by step how to install this on Ubuntu 18.04 and how to configure all the settings. In fact my x52pro works great by default but I would like to know how to turn off the led lights.

Thank you in advance!

**Comment by nirenjan** [comment]
The Readme should have covered the build and install instructions, which are fairly simple.

However, if you don't want to build it from source, I've created a Debian package in the [releases page for v0.2.0](https://github.com/nirenjan/x52pro-linux/releases/tag/v0.2.0), just download and install the [x52pro-linux1](https://github.com/nirenjan/x52pro-linux/releases/download/v0.2.0/x52pro-linux-dev_0.2.0-1_amd64.deb) Debian package, and you should be able to run `x52cli` to control the LED.

Bear in mind that the settings are not preserved, and therefore they must be reset after the joystick is unplugged and plugged in, or after a reboot.
