### ISSUE TITLE
Configure Error on OSX Catalina

### ISSUE THREAD

**Issue by francoisgfx** [nirenjan/x52pro-linux#18]
Hi,

At the configure stage I'm having an error. Here is what I have in the config.log : 
`
configure:3851: checking for ar
configure:3867: found /opt/local/bin/ar
configure:3878: result: ar
configure:3904: checking the archiver (ar) interface
configure:3920: gcc -c -g -O2  conftest.c >&5
configure:3920: $? = 0
configure:3922: ar cru libconftest.a conftest.o >&5
/opt/local/bin/ranlib: object: libconftest.a(conftest.o) malformed object (unknown load command 1)
ar: internal ranlib command failed
configure:3925: $? = 1
configure:3931: ar -NOLOGO -OUT:conftest.lib conftest.o >&5
ar: illegal option -- N
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
configure:3934: $? = 1
configure:3953: result: unknown
configure:3969: error: could not determine ar interface
`

I'm running OSX Catalina 10.15.4
uname -m = x86_64
uname -r = 19.4.0
uname -s = Darwin
uname -v = Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64

**Comment by nirenjan** [comment]
This is a bit weird, the ar on my OSX (I'm running High Sierra BTW, have a fairly old Macbook), resides at `/usr/bin/ar`, whereas your snippet seems to indicate `/opt/local/bin/ar`. I'm not sure if you've installed a third party GCC, or are using MacPorts.

Can you check if Apple's ar is present at `/usr/bin/ar`? If so, can you temporarily update your PATH to prefer `/usr/bin` over `/opt/local/bin`?

There's a similar reported issue in another project - see https://github.com/commercialhaskell/stack/issues/4380#issuecomment-435262763
