### ISSUE TITLE
Typo in install instructions, causes rules to be written to /rules.d

### ISSUE THREAD

**Issue by lbeltrame** [nirenjan/x52pro-linux#24]
**Describe the bug**

The `pkg-config` invocation should be:

```
pkg-config --variable=udevdir udev
```

Otherwise, at least on my openSUSE system, I get

```
pkg-config --variable=udev
Please specify at least one package name on the command line.
```

This causes the udev rules to be written to `/rules.d` because the subprocess does not return any output.

**To Reproduce**
1. Execute the configure call in `INSTALL.md`

**Comment by nirenjan** [comment]
Thanks for the bug report. I've fixed it in the master branch. Please reopen if you still have issues.
