### ISSUE TITLE
Allow to specify the group used in udev rules

### ISSUE THREAD

**Issue by lbeltrame** [nirenjan/x52pro-linux#25]
**Is your feature request related to a problem? Please describe.**
Not all Linux distributions use `plugdev` for groups allowed to access input devices. openSUSE, for example, has an `input` group.

**Describe the solution you'd like**
Keep `plugdev` as default, but allow changing this in a `configure` call.

**Describe alternatives you've considered**
Replacing the group manually before installing, but for any distribution doing packaging that would be probably extra effort, and potentially error prone.

**Comment by nirenjan** [comment]
@lbeltrame, can you try the `feature/custom-udev-input-group` branch and see if it works as you intended? If this is OK, I'll merge it to the master branch.

Thanks for the report.

**Comment by nirenjan** [comment]
I forgot to mention, I've updated the INSTALL.md file in that branch with the instructions for customizing the input group.

**Comment by lbeltrame** [comment]
The file is correctly generated, as far as I can see. Thanks for the prompt adjustment!

**Comment by nirenjan** [comment]
Fix merged in master branch.
