### ISSUE TITLE
X52Pro Second POV hat (metal one) LED

### ISSUE THREAD

**Issue by LittleCannon** [nirenjan/x52pro-linux#36]
**Is your feature request related to a problem? Please describe.**
Unable to change LED color on second POV hat (metal one)

**Describe the solution you'd like**
To be able to change second POV hat LED color

**Describe alternatives you've considered**
---

**Additional context**
---

**Comment by nirenjan** [comment]
I don't believe the second POV LED can be controlled. There is only a blink feature, which blinks it on and off, but I haven't found any method to actually change the color. This is pretty much based on the Windows control panel interface, which can change the color of every LED (or On/Off only for the Fire button & throttle LEDs), and that doesn't have a control for the second POV.

That said, it might need a little reverse engineering to see if there is a hidden control message that can control that LED. I just haven't tried it.

**Comment by nirenjan** [comment]
I gave it a shot, but it seems like a limitation of the hardware that you cannot control the hat LED.

**Comment by nirenjan** [comment]
Seems like a hardware limitation, I haven't found any control message that can modify the hat LED, apart from the blink.

**Comment by LittleCannon** [comment]
Understood,
I was just playing with new configurations and profiles, and I noticed that HAT LED is not on the list.

Tnx for trying.
