### ISSUE TITLE
12 hour clock display broken for 12 AM

### ISSUE THREAD

**Issue by nirenjan** [nirenjan/x52pro-linux#5]
When the user sets the clock to a time that represents 12:00:00 AM to 12:59:59 AM in the chosen location (local/GMT), and the clock is set to display in 12 Hour mode, the MFD displays 00 AM, i.e. the hour is displayed as 0.

This appears to be a known hardware issue, at least with my unit. Setting the hour value to 12 corresponds to 12 PM, so that won't fix the problem.

**Comment by nirenjan** [comment]
This seems to be a problem even on clock 2 & clock 3 - 12 AM is displayed as 00 AM.

**Comment by rogerxxxx** [comment]
Do you know of anybody that actually makes use of the MFD?

If so, the only method I can think of, is when there is a scenario where the computer keyboard is hidden from the user.  (ie. Arcade game or setup similar to a real simulation.)

**Comment by Mange** [comment]
I, for one, use it.

To see the time. 😉

lör 5 dec. 2015 16:52 rogerxxxx <notifications@github.com> skrev:
